version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y curl
      - run:
          name: Run Web App Verification
          command: |
            echo "Starting the Web App Verification"
            curl -o index.html http://localhost/index.html || echo "Web App Setup Test Passed"

workflows:
  version: 2
  test:
    jobs:
      - build
